#define TK_SEMI                            1
#define TK_EXPLAIN                         2
#define TK_QUERY                           3
#define TK_PLAN                            4
#define TK_BEGIN                           5
#define TK_TRANSACTION                     6
#define TK_DEFERRED                        7
#define TK_IMMEDIATE                       8
#define TK_EXCLUSIVE                       9
#define TK_COMMIT                         10
#define TK_END                            11
#define TK_ROLLBACK                       12
#define TK_CREATE                         13
#define TK_TABLE                          14
#define TK_TEMP                           15
#define TK_LP                             16
#define TK_RP                             17
#define TK_AS                             18
#define TK_COMMA                          19
#define TK_ID                             20
#define TK_ABORT                          21
#define TK_AFTER                          22
#define TK_ANALYZE                        23
#define TK_ASC                            24
#define TK_ATTACH                         25
#define TK_BEFORE                         26
#define TK_CASCADE                        27
#define TK_CAST                           28
#define TK_CONFLICT                       29
#define TK_DATABASE                       30
#define TK_DESC                           31
#define TK_DETACH                         32
#define TK_EACH                           33
#define TK_FAIL                           34
#define TK_FOR                            35
#define TK_IGNORE                         36
#define TK_INITIALLY                      37
#define TK_INSTEAD                        38
#define TK_LIKE_KW                        39
#define TK_MATCH                          40
#define TK_KEY                            41
#define TK_OF                             42
#define TK_OFFSET                         43
#define TK_PRAGMA                         44
#define TK_RAISE                          45
#define TK_REPLACE                        46
#define TK_RESTRICT                       47
#define TK_ROW                            48
#define TK_STATEMENT                      49
#define TK_TRIGGER                        50
#define TK_VACUUM                         51
#define TK_VIEW                           52
#define TK_REINDEX                        53
#define TK_RENAME                         54
#define TK_CTIME_KW                       55
#define TK_OR                             56
#define TK_AND                            57
#define TK_NOT                            58
#define TK_IS                             59
#define TK_BETWEEN                        60
#define TK_IN                             61
#define TK_ISNULL                         62
#define TK_NOTNULL                        63
#define TK_NE                             64
#define TK_EQ                             65
#define TK_GT                             66
#define TK_LE                             67
#define TK_LT                             68
#define TK_GE                             69
#define TK_ESCAPE                         70
#define TK_BITAND                         71
#define TK_BITOR                          72
#define TK_LSHIFT                         73
#define TK_RSHIFT                         74
#define TK_PLUS                           75
#define TK_MINUS                          76
#define TK_STAR                           77
#define TK_SLASH                          78
#define TK_REM                            79
#define TK_CONCAT                         80
#define TK_UMINUS                         81
#define TK_UPLUS                          82
#define TK_BITNOT                         83
#define TK_STRING                         84
#define TK_JOIN_KW                        85
#define TK_CONSTRAINT                     86
#define TK_DEFAULT                        87
#define TK_NULL                           88
#define TK_PRIMARY                        89
#define TK_UNIQUE                         90
#define TK_CHECK                          91
#define TK_REFERENCES                     92
#define TK_COLLATE                        93
#define TK_AUTOINCR                       94
#define TK_ON                             95
#define TK_DELETE                         96
#define TK_UPDATE                         97
#define TK_INSERT                         98
#define TK_SET                            99
#define TK_DEFERRABLE                     100
#define TK_FOREIGN                        101
#define TK_DROP                           102
#define TK_UNION                          103
#define TK_ALL                            104
#define TK_EXCEPT                         105
#define TK_INTERSECT                      106
#define TK_SELECT                         107
#define TK_DISTINCT                       108
#define TK_DOT                            109
#define TK_FROM                           110
#define TK_JOIN                           111
#define TK_USING                          112
#define TK_ORDER                          113
#define TK_BY                             114
#define TK_GROUP                          115
#define TK_HAVING                         116
#define TK_LIMIT                          117
#define TK_WHERE                          118
#define TK_INTO                           119
#define TK_VALUES                         120
#define TK_INTEGER                        121
#define TK_FLOAT                          122
#define TK_BLOB                           123
#define TK_REGISTER                       124
#define TK_VARIABLE                       125
#define TK_EXISTS                         126
#define TK_CASE                           127
#define TK_WHEN                           128
#define TK_THEN                           129
#define TK_ELSE                           130
#define TK_INDEX                          131
#define TK_ALTER                          132
#define TK_TO                             133
#define TK_ADD                            134
#define TK_COLUMNKW                       135
